### ISSUE TITLE
EntityViewRepository findAll(start,max) fails with ClassCastException

### ISSUE THREAD

**Issue by sharadborhade** [Blazebit/blaze-persistence#720]
findAll(start, max) method of the Repository fails with `java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long` for **eclipselink embedded composite primary key**. It works with hibernate 5.0.12.Final.

I am referring [deltaspike-data-rest example](https://github.com/Blazebit/blaze-persistence/tree/master/examples/deltaspike-data-rest) with tomcat web server and CDI injection.

### Expected behavior
findAll(start,max) should return the `List<CompositeView>`

### Actual behavior
       
    Exception is:
    Caused by: org.apache.deltaspike.data.api.QueryInvocationException: Failed calling Repository: [Repository=com.blaze.poc.CompositeViewRepository,entity=com.blaze.poc.CompositeKeyEntity,method=findAll,exception=class java.lang.reflect.InvocationTargetException,message=null
		at com.blazebit.persistence.deltaspike.data.impl.builder.EntityViewDelegateQueryBuilder.invoke(EntityViewDelegateQueryBuilder.java:118)
		at com.blazebit.persistence.deltaspike.data.impl.builder.EntityViewDelegateQueryBuilder.execute(EntityViewDelegateQueryBuilder.java:61)
		... 14 more
	Caused by: java.lang.reflect.InvocationTargetException
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.blazebit.persistence.deltaspike.data.impl.builder.EntityViewDelegateQueryBuilder.invoke(EntityViewDelegateQueryBuilder.java:113)
		... 15 more
	Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
		at com.blazebit.persistence.impl.PaginatedTypedQueryImpl.getResultList(PaginatedTypedQueryImpl.java:158)
		at com.blazebit.persistence.impl.PaginatedTypedQueryImpl.getResultList(PaginatedTypedQueryImpl.java:45)
		at com.blazebit.persistence.deltaspike.data.base.handler.AbstractEntityViewAwareRepositoryHandler.findAll(AbstractEntityViewAwareRepositoryHandler.java:286)
		... 20 more

### Steps to reproduce

1. Downloaded [deltaspike-data-rest example](https://github.com/Blazebit/blaze-persistence/tree/master/examples/deltaspike-data-rest)
2. Marked config beans to **ApplicationScoped**
3. Created CompositeKeyEntity with **embedded** CompositePK and EntityView (CompositeView, CompositeIdView). CompositePK contains 2 fields (**String, java.sql.Timestamp**)
4. Created CompositeViewRepository by extending EntityViewRepository<CompositeKeyEntity, CompositeView, CompositePK>. 
5. Created test class to test default repository methods. findBy method works, but findAll(0,10) fails.

### Environment

Version: 1.3.1/1.3.0
JPA-Provider: Eclipselink 2.6.4, Deltaspike 1.8.1       
DBMS: DB2 11 for z/OS, Driver: IBM Data Server Driver for JDBC and SQLJ  Version: 4.21.29               
Web Server: Tomcat, CDI

**Comment by beikov** [comment]
Thanks for the report, but I couldn't reproduce it with H2 on the latest TomEE. I'm not sure, but this might be a DB2 + EclipseLink related issue

**Comment by sharadborhade** [comment]
Thank you for the quick look, but I think it could be an issue with blaze deltaspike integration as EntityRepository.findAll(start,max) method of deltaspike data works with DB2 + eclipselink, but when I use EntityViewRepository of blaze deltaspike integration then it fails with the ClassCastException.

**Comment by beikov** [comment]
Do you think you could share that example via e.g. a PR? I just tried to reproduce this with DB2 but couldn't.

**Comment by beikov** [comment]
I finally reproduced it. Configuring DB2 for TomEE was harder than I thought. Looking into this now

**Comment by beikov** [comment]
IMO this is an EclipseLink bug. I create a query like `entityManager.createQuery("select count(*) from ...", Long.class)` and rightfully expect the result to be of the type `Long`, but EclipseLink uses the type the JDBC driver provides, which in case of DB2 is `Integer`. I will try to workaround it, but this is almost certainly going to blow up at other places where you are using a count query as well.

**Comment by sharadborhade** [comment]
Thanks for the quick analysis. Will wait for the fix.

**Comment by beikov** [comment]
There is an open PR associated with this issue that contains the workaround. You can build it yourself for now if you want to give it a try. I will try to do a release later this week, but I can't promise anything yet.

**Comment by sharadborhade** [comment]
Thanks. will check and confirm.

**Comment by sharadborhade** [comment]
Count query works, but it fails in next step with below exception. 
    
    DB2 SQL Error: SQLCODE=-199, SQLSTATE=42601, SQLERRMC=NULLS;FETCH , EXCEPT MINUS UNION ), DRIVER=4.21.29

SQL query works after removing `NULLS LAST` from order by. As per this [link](https://www.ibm.com/support/knowledgecenter/en/SSEPEK_11.0.0/sqlref/src/tpc/db2z_sql_orderbyclause.html), DB2 for z/OS does not support NULLS LAST.

`Deltaspike + Eclipselink + DB2` generates the query without NULLS LAST
`Blaze + Deltaspike + Hibernate + DB2` works and generates the query without NULLS LAST

**Comment by beikov** [comment]
Seems like this is another EclipseLink issue. I can look into it, maybe we can automatically adapt the EclipseLink DatabasePlatform to yield the correct behavior.

**Comment by sharadborhade** [comment]
Thanks

**Comment by beikov** [comment]
The latest push should fix the issues with the null precedence handling on DB2 with EclipseLink

**Comment by sharadborhade** [comment]
I noticed EntityRepository.findAll(start, max) fails with NullPointerException. 

    Caused by: java.lang.NullPointerException
        at com.blazebit.persistence.deltaspike.data.impl.handler.EntityViewRepositoryHandler.idAttribute(EntityViewRepositoryHandler.java:97)
        at com.blazebit.persistence.deltaspike.data.base.handler.AbstractEntityViewAwareRepositoryHandler.findAll(AbstractEntityViewAwareRepositoryHandler.java:194)

It seems to be because of viewClass() being null in the EntityViewRepositoryHandler.idAttribute() method.

**Comment by sharadborhade** [comment]
No. I am using Deltaspike's EntityRepository<E,PK> which does not require view class. I am passing Entity class and PK class. 
EntityViewRepositoryHandler seems to be handling the calls for Deltaspike's EntityRepository.

**Comment by beikov** [comment]
Hmm, that's odd. I'll look into this, but probably won't be able to finish this today

**Comment by beikov** [comment]
I pushed something that should do it, but I wasn't able to do any further tests yet. Would be nice if you could let me know so I can take a deeper look tomorrow.

**Comment by sharadborhade** [comment]
Thanks for the immediate fix. findAll(1,10) works, but it is fetching more records than expected. It seems offset needs to be set to the query.

**Comment by beikov** [comment]
Sorry for the issues, this one was an oversight. We mainly tested the entity view parts and apparently didn't notice that the entity related stuff was partly non-functional. I pushed the fix to the PR. When you are done testing/evaluating, I will do another release.

**Comment by beikov** [comment]
@sharadborhade can you confirm it works as expected now? I'd like to do a release this week with all those fixes.

**Comment by sharadborhade** [comment]
null precedence issue [723](https://github.com/Blazebit/blaze-persistence/issues/723) still exists. Other issues are fixed.

I noticed [getDbms](https://github.com/beikov/blaze-persistence/blob/8494cc4a17262282eb6b41044a8134f2f1717070/integration/eclipselink/src/main/java/com/blazebit/persistence/integration/eclipselink/function/EclipseLinkEntityManagerIntegrator.java#L58) method returns null dbms.

Issue is with Eclipse + DB2 for z/OS. As per IBM documentation, DB2 for Linux, UNIX, and Windows supports NULLS LAST.

**Comment by beikov** [comment]
Yeah you are right, I forgot to implement `getDbms` for eclipselink 🤦‍♂️

**Comment by sharadborhade** [comment]
@beikov, any update on the null precedence issue?

**Comment by beikov** [comment]
The PR https://github.com/Blazebit/blaze-persistence/pull/721 should fix the issue. I'm about to merge that now. Would be great if you could verify it works properly

**Comment by sharadborhade** [comment]
Still facing the same issue. NULLS LAST is appended to the sql query and sql query fails with below issue.

```
DB2 SQL Error: SQLCODE=-199, SQLSTATE=42601, SQLERRMC=NULLS;FETCH , EXCEPT MINUS UNION ), DRIVER=4.21.29
```

**Comment by beikov** [comment]
Found the issue, I forgot to enable the workaround/optimization. I tested it now and can confirm that tests which failed before, are now running fine.
