### ISSUE TITLE
StackOverflowError during reflection

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#848]
### Description

running `myrepo.save()` on a entity wit

```java
@Entity
@DiscriminatorValue("ATOMARSYSTEM")
@DynamicUpdate
@Data
@EqualsAndHashCode(callSuper = true)
public class AtomarSystemPermission extends PermissionImpl implements AtomarPermission
{
  @Column(columnDefinition = "VARCHAR(255)", unique = true)
  @EqualsAndHashCode.Include
  String perm;
```

and its parent class

```java
@Entity
@Table(name = "permission_composite")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(
  name = "discriminator",
  discriminatorType = DiscriminatorType.STRING,
  length = 32
)
@Data
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public abstract class PermissionImpl implements Serializable, Permission
{
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(columnDefinition = "INT(10)")
  @EqualsAndHashCode.Include
  private Long id;
```

### Actual behavior

```
java.lang.StackOverflowError
	at java.base/java.util.LinkedHashMap.newNode(LinkedHashMap.java:256)
	at java.base/java.util.HashMap.putVal(HashMap.java:626)
	at java.base/java.util.HashMap.put(HashMap.java:607)
	at java.base/java.util.HashSet.add(HashSet.java:220)
	at com.blazebit.reflection.ReflectionUtils.addSuperTypes(ReflectionUtils.java:168)
	at com.blazebit.reflection.ReflectionUtils.getSuperTypes(ReflectionUtils.java:159)
	at com.blazebit.reflection.ReflectionUtils.resolveTypeVariableType(ReflectionUtils.java:359)
	at com.blazebit.reflection.ReflectionUtils.resolveTypeVariable(ReflectionUtils.java:461)
	at com.blazebit.reflection.ReflectionUtils.resolveType(ReflectionUtils.java:281)
	at com.blazebit.reflection.ReflectionUtils.resolveTypeVariable(ReflectionUtils.java:462)
	at com.blazebit.reflection.ReflectionUtils.resolveType(ReflectionUtils.java:281)
	at com.blazebit.reflection.ReflectionUtils.resolveTypeVariable(ReflectionUtils.java:462)
	at com.blazebit.reflection.ReflectionUtils.resolveType(ReflectionUtils.java:281)
	at com.blazebit.reflection.ReflectionUtils.resolveTypeVariable(ReflectionUtils.java:462)
	at com.blazebit.reflection.ReflectionUtils.resolveType(ReflectionUtils.java:281)
	at com.blazebit.reflection.ReflectionUtils.resolveTypeVariable(ReflectionUtils.java:462)
.....
```

### Steps to reproduce
It might be again related to a natural-id mapping, since this was one too. It is the same one we handle in  https://github.com/Blazebit/blaze-persistence/issues/846 just this type not during model mapping but during repository save

### Environment
Version:  9.9-snapshot based on non-HEAD https://github.com/Blazebit/blaze-persistence/issues/846
JPA-Provider: hibernate 5.4.5
DBMS:  mariadb10.3
Application Server: spring boot 2.1.7

**Comment by EugenMayer** [comment]
Disabling blaze-persistence does fix it, if that is yet not obvious in this case :)

**Comment by JWGmeligMeyling** [comment]
Have you bumped blaze reflections utils as I asked you to do?

**Comment by JWGmeligMeyling** [comment]
https://mvnrepository.com/artifact/com.blazebit/blaze-common-utils/0.1.17 Should fix this

**Comment by EugenMayer** [comment]
@JWGmeligMeyling i already tested with 0.1.17 `com.blazebit:blaze-common-utils:0.1.17` - it does not fix it

**Comment by JWGmeligMeyling** [comment]
Ok weird, 0.1.17 fixed the exact stracktrace but apparently there are other occasions we do not consider yet. Hopefully we're able to reproduce it.

**Comment by EugenMayer** [comment]
After a brief discussion with @beikov he explained that this issue is because i was using a generic on my tepository

```java

@Repository
public interface Somerepo<T extends PermissionImpl> extends JpaRepository<T, Long> {
..
}
```

This is yet not supported and actually also very unusal - i removed the generic using concrete types now and things went back to normal
